# Generated by Django 5.2.4 on 2025-08-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack'), ('Design', 'Design'), ('Blockchain', 'Blockchain'), ('DevOps', 'DevOps'), ('AI', 'AI'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
